### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by bbalaji-ucsd** [BrickSchema/Brick#22]
- [ ]  Add support for units

- [ ]  Include smart home devices

- [ ]  Interface with Haystack

- [ ] Interface with IFC

- [ ] Basic idioms:
   - [ ] represent a setpoint
   - [ ] represent an HVAC system w/ heating+cooling loops

- [ ] represent a lighting system

- [ ] represent metering infrastructure
